# Generated by Django 5.2.1 on 2025-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='actus/')),
                ('badge', models.CharField(default='Événement', max_length=50)),
                ('badge_color', models.CharField(default='primary', max_length=30)),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
