# Generated by Django 5.2.1 on 2025-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='profs/')),
                ('domaine', models.CharField(max_length=200)),
                ('publications', models.TextField(help_text='Séparez les publications par un saut de ligne')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
