# Generated by Django 5.2.1 on 2025-06-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_professeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(max_length=100)),
                ('email_demandeur', models.EmailField(max_length=254)),
                ('domaine_demandeur', models.CharField(max_length=50)),
                ('membre', models.CharField(max_length=100)),
                ('nom_autre', models.CharField(blank=True, max_length=100, null=True)),
                ('poste_autre', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.CharField(max_length=255)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
